### Variables
@baseUrl = http://localhost:8080/api/v1

### Login User
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### Change Password User
POST {{baseUrl}}/auth/password
Content-Type: application/json
Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY2OTc5MzcsInVzZXJfaWQiOjF9.tfDee6K8DvtzQOhLpWLWxtdbwSwbmNHh6C9RIRW2Pn0

{
    "password": "admin2"
}